name: Add to comprehensive project

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  repository-projects: write

jobs:
  add-to-comprehensive-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/chronocosm/projects/1
          github-token: ${{ secrets.CHRONOCOSM_GITHUB_ACCESS_TOKEN }}
